# Generated by Django 6.0.7 on 2026-07-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moviem',
            new_name='Movie',
        ),
    ]
