# Generated by Django 6.0.7 on 2026-07-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_details_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
