# Generated by Django 6.0.7 on 2026-08-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_genre_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='details',
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.CharField(blank=True, help_text='e.g. 2h 34m', max_length=200, null=True),
        ),
    ]
